### ISSUE TITLE
Add possibility to generate payload dynamically

### ISSUE THREAD

**Issue by shvydky** [schollz/peerdiscovery#17]
In my case, it is required to send different payloads in every broadcast.

I propose to have an optional function pointer in `Settings` that will return payload on demand. In case when this pointer is `nil` the implementation should fallback to `Payload` field.

I will try to implement this in the fork and create PR.

@schollz, please let me know what do you think about my idea?

**Comment by schollz** [comment]
Sounds great! Feel free to add
