### ISSUE TITLE
Ignoring configured address family can lead to deadlock on MacOS

### ISSUE THREAD

**Issue by thewilli** [schollz/peerdiscovery#23]
After [getting the list of interfaces](https://github.com/schollz/peerdiscovery/blob/66163e1/peerdiscovery.go#L166), interfaces not having at least one address of the [configured address family](https://github.com/schollz/peerdiscovery/blob/66163e1/peerdiscovery.go#L68) are not skipped.

[Sending](https://github.com/schollz/peerdiscovery/blob/66163e1/peerdiscovery.go#L255) a multicast with an IPv4 connection on an IPv6-only interface results (at least on MacOS) in a deadlock.

Additionally, you should check the interface flags if is up and if it supports multicast at all.

This issue might be the root cause of https://github.com/schollz/croc/issues/313

**Comment by schollz** [comment]
maybe this will fix it: https://github.com/schollz/peerdiscovery/compare/v1.6.3...v1.6.4#diff-2579afdfe9dbc2fd03f59fa3dd5f31396c4107cf1ca5c05afe433f163a00c276R171-R201 ?

**Comment by thewilli** [comment]
please consider #24 which might be a bit more straightforward and moves the code out of the function to improve readability

**Comment by thewilli** [comment]
it does for me 😉 and it reduces some overhead as almost all of my 19 network interfaces were skipped

**Comment by schollz** [comment]
That's great! Thanks for the update. Merged and added to croc
