### ISSUE TITLE
Doesn't work with AllowSelf on windows

### ISSUE THREAD

**Issue by phanirithvij** [schollz/peerdiscovery#25]
I've tried the IPV4 example with `AllowSelf` set to true on windows, without any other changes but It doesn't discover other local peers.

But it works on my android 10 device android/arm64 cross-compiled on windows run via termux. Windows can't discover the android peer but android can discover another instance of itself and also windows (in the same wifi).

**Comment by schollz** [comment]
would accept PR

**Comment by phanirithvij** [comment]
I no longer use windows and I don't think I can fix this issue even if I did.
