### ISSUE TITLE
Does this discover peers that are not also running this software?

### ISSUE THREAD

**Issue by nathanpaulyoung** [schollz/peerdiscovery#3]
Does this discover peers that are not also running this software, or do all peers need to be running this in some sort of "listening" mode?

**Comment by schollz** [comment]
There is a specific port and address specified, so it will discover anyone broadcasting on with that address and port

**Comment by nathanpaulyoung** [comment]
I skimmed the example and didn't see where those are specified. Are you saying that the address and port are configurable, or that there is a hardcoded port and/or address range that it checks? Additionally, does it require a particular response payload, or is it basically just looking for an ACK?

**Comment by schollz** [comment]
They are specified in the settings: https://github.com/schollz/peerdiscovery/blob/master/peerdiscovery.go#L25

In the example I used the defaults.

The payload is optional

**Comment by nathanpaulyoung** [comment]
Google translating the abive questions:
1. Is it limited to LAN?
2. Does it need a server to relay the broadcast?

**Comment by schollz** [comment]
@zxbit2011 @nathanpaulyoung 

1. Yes.
2. No - each instance does "broadcasting" and "listening" so in that sense, each instance is a server and a client.
