### ISSUE TITLE
Fantastic library, unfortunately not compatible with GKE

### ISSUE THREAD

**Issue by mkuratczyk** [schollz/peerdiscovery#39]
Hi. Not really an issue as such - I just want to leave these two comments:

1. This is a fantastic library for what it does. It took me quite some time to find it but once I did - it took like a minute to try the demo, a minute to include in my app and maybe another minute to build an OCI image and verify it works on Kubernetes locally. So smooth. Great work!

2. Unfortunately, then I deployed this to GKE and learned the hard way that [GKE doesn't support multicast](https://www.googlecloudcommunity.com/gc/Infrastructure-Compute-Storage/Does-GCP-support-multicast-IGMP-based-or-otherwise-like-overlay/m-p/598406#M3366) so unfortunately I can't this library for what I needed.

I'm still searching for something like this that would work on GKE. https://github.com/jgroups-extras/jgroups-kubernetes works perfectly for the Java app I have - rather than multicast, it uses the Kubernetes API for the initial discovery of IPs to (try to) connect to. So far I couldn't find anything like this for Go.

Best,

**Comment by mkuratczyk** [comment]
Closing the issue. I just wanted to leave the comment in case someone else searches for "GKE".

**Comment by schollz** [comment]
@mkuratczyk is this comparable to peerdicovery though?

from memberlist: 

> Join an existing cluster by specifying at least one known member.

peerdiscovery works without any known members. would there have to be an "always online" member to facilitate?

**Comment by mkuratczyk** [comment]
It's not exactly the same but similar enough for what I need. Indeed, it needs a list but I just give it a Kubernetes service which matches all pods that could potentially discover each other. As the pods start, Kubernetes starts returning them when resolving the DNS of the service so that initial list is populated by the pods that already started. I've only run a few experiments for now but so far it did exactly what I wanted.

Just to explain my use case if anyone's curious: I'm working on a load generation mechanism where we compare performance of different RabbitMQ versions under the same load. I don't want to start generating load on any environments until all environments are ready, so all I really want is just "wait for the expected number of nodes". We've been using this mechanism with Java+jgroups for years but now I need a similar thing in Go. The final result is something like this:
https://www.rabbitmq.com/blog/2023/05/17/rabbitmq-3.12-performance-improvements#311-non-lazy-vs-312
each 5-minute period is a separate test (different workload) then there's a break and then another test, which should once again synchronize the environments by waiting until all environments are ready.
